// The grading checklists: what counts, per regulation area, and how much.
//
// Each area has a fixed list of provisions ("elements"). The tier agent's
// only job is to say which elements a state has enacted and which bill
// enacts each one; the tier itself is computed by rule in ./formulas.ts.
// Every element carries a level (1 to 4), the tier that kind of provision
// belongs to, and the rubric lines describe what each tier looks like in plain words.
//
// This file is the source of truth for both the pipeline (convex/seedData.ts
// spreads the rubrics into the regulationAreas table) and the /scoring page.
// Change an element here and re-run `retier` so the grades follow.

export type ElementLevel = 1 | 2 | 3 | 4;

export type ChecklistElement = {
  /** Stable id, unique within the area. Stored on grades. */
  id: string;
  /** Under 10 words, a provision a reader can recognise. */
  label: string;
  /** The tier this provision belongs to: 1 is a first, narrow duty; 4 completes a regime. */
  level: ElementLevel;
  /** One sentence on what counts. The agent reads this. */
  test: string;
};

export type AreaChecklist = {
  key: string;
  /** Five lines, index = tier 0 to 4. */
  rubric: [string, string, string, string, string];
  elements: ChecklistElement[];
};

export const CHECKLISTS: Record<string, AreaChecklist> = {
  frontier: {
    key: "frontier",
    rubric: [
      "No obligations on large-model developers.",
      "A study, task force, or voluntary framework on frontier risk.",
      "Disclosure duties: published safety frameworks or incident reports to the state.",
      "Mandatory testing or assessment before deployment, with agency enforcement.",
      "Pre-deployment duties backed by penalties and whistleblower protections.",
    ],
    elements: [
      { id: "study", label: "State study or voluntary framework on frontier risk", level: 1, test: "A statute creates a task force, commission, or study of large-model risks, or invites developers into a voluntary framework." },
      { id: "framework", label: "Developers must publish a safety framework", level: 2, test: "Developers above a size or compute threshold must publish how they assess and mitigate catastrophic risk." },
      { id: "incidents", label: "Critical incident reporting to the state", level: 2, test: "Developers must report safety incidents (loss of control, misuse enabling mass harm) to a state office within a set time." },
      { id: "testing", label: "Mandatory pre-deployment risk assessment", level: 3, test: "Developers must test or assess a frontier model for catastrophic risk before release and keep records of it." },
      { id: "enforcement", label: "Agency enforcement with civil penalties", level: 3, test: "A named agency or the attorney general can enforce the duties with fines." },
      { id: "whistleblower", label: "Whistleblower protections for lab employees", level: 4, test: "Employees who report catastrophic-risk concerns are protected from retaliation, with a channel to the state." },
      { id: "liability", label: "Duty of care or shutdown capability with liability", level: 4, test: "Developers owe a duty of care for catastrophic harms, or must keep a shutdown capability, with liability or penalties for breach." },
    ],
  },
  transparency: {
    key: "transparency",
    rubric: [
      "No AI disclosure duties.",
      "Disclosure in one narrow use, such as political ads or chatbots.",
      "Disclosure across several consumer-facing uses, or provenance and training-data duties.",
      "Notice when AI drives a consequential decision, and developer-to-deployer documentation.",
      "Notice, explanation, and appeal rights across sectors, with enforcement.",
    ],
    elements: [
      { id: "narrow", label: "Disclosure in one narrow use", level: 1, test: "AI use must be disclosed in a single setting, such as political ads, telemarketing, or a chatbot warning notice." },
      { id: "genai-notice", label: "Notice that generative AI produced a communication", level: 1, test: "Businesses must tell consumers when a message, image, or document was generated by AI." },
      { id: "provenance", label: "Provenance or watermark duties for AI outputs", level: 2, test: "Generative AI providers must embed or offer provenance data, watermarks, or a detection tool." },
      { id: "training-data", label: "Training data documentation", level: 2, test: "Developers must publish a summary of the data used to train generative models." },
      { id: "adm-notice", label: "Notice of automated consequential decisions", level: 3, test: "People must be told when an automated system made or materially shaped a decision about housing, credit, employment, insurance, education, or public services." },
      { id: "deployer-docs", label: "Developer-to-deployer documentation", level: 3, test: "Developers of high-risk systems must give deployers documentation on intended use, limits, and testing." },
      { id: "explain-appeal", label: "Right to explanation and appeal", level: 4, test: "People can get the reasons for an automated decision and have a human review it." },
      { id: "enforcement", label: "Agency enforcement with penalties", level: 4, test: "A named agency or the attorney general can fine a business for failing a disclosure duty." },
    ],
  },
  chatbots: {
    key: "chatbots",
    rubric: [
      "No rules for conversational AI.",
      "Bots must identify themselves as AI.",
      "Disclosure plus self-harm response protocols or reporting.",
      "Age-specific limits on companion features, design, and data use.",
      "Audits or age verification and a private right of action for harms to minors.",
    ],
    elements: [
      { id: "identify", label: "Bots must identify themselves as AI", level: 1, test: "A chatbot must disclose it is AI when asked or when a reasonable person could think it is human." },
      { id: "no-impersonation", label: "No posing as a licensed professional", level: 2, test: "Bots may not present themselves as licensed therapists, doctors, or other professionals." },
      { id: "crisis", label: "Self-harm and crisis response protocol", level: 2, test: "Operators must maintain a protocol that detects self-harm content and refers users to crisis services." },
      { id: "reporting", label: "Annual safety reporting to the state", level: 2, test: "Operators must report crisis referrals or safety measures to a state office each year." },
      { id: "minor-limits", label: "Age-specific limits for minors", level: 3, test: "For known minors: break reminders, sexual content blocks, parental controls, or usage limits." },
      { id: "design", label: "Limits on engagement-maximizing design or minors' data", level: 3, test: "Restrictions on features designed to maximise engagement of minors or on collecting and selling their data." },
      { id: "audits", label: "Independent audits or age verification", level: 4, test: "Operators must undergo third-party audits or verify user age." },
      { id: "pra", label: "Private right of action", level: 4, test: "People harmed by a chatbot can sue for damages." },
    ],
  },
  gov: {
    key: "gov",
    rubric: [
      "No rules on agency use of AI.",
      "Task force, officer, or inventory of systems in use.",
      "Procurement standards and published use policies.",
      "Impact assessments before deployment and human review of decisions.",
      "Binding prohibitions on high-risk uses with independent oversight.",
    ],
    elements: [
      { id: "taskforce", label: "Task force, study, or chief AI officer", level: 1, test: "A statute creates a body or officer responsible for state government AI." },
      { id: "inventory", label: "Inventory of agency AI systems", level: 1, test: "Agencies must catalogue the AI systems they use and publish or report the list." },
      { id: "procurement", label: "Procurement standards for AI", level: 2, test: "Rules govern how agencies buy AI: vendor disclosures, testing, or contract terms." },
      { id: "policies", label: "Published agency use policies", level: 2, test: "Agencies must adopt and publish policies on acceptable AI use, or follow statewide standards." },
      { id: "assessment", label: "Impact assessment before deployment", level: 3, test: "Agencies must assess a high-risk system's effects on rights, safety, or fairness before using it." },
      { id: "human-review", label: "Human review of automated decisions", level: 3, test: "Decisions affecting benefits, rights, or liberty cannot be made by AI alone; a person must review." },
      { id: "prohibitions", label: "Binding prohibitions on specific uses", level: 4, test: "The state bans agencies from using AI for named purposes, such as social scoring or real-time biometric surveillance." },
      { id: "oversight", label: "Independent oversight with audit power", level: 4, test: "An independent body can audit agency AI systems and order changes." },
    ],
  },
  dc: {
    key: "dc",
    rubric: [
      "No data-center-specific rules.",
      "Reporting or disclosure of energy and water use.",
      "Grid-impact studies, interconnection review, or siting review for large loads.",
      "Large-load tariffs that shift grid costs to operators, and conditioned incentives.",
      "Enforceable operating standards for large loads, with penalties.",
    ],
    elements: [
      { id: "reporting", label: "Energy or water use reporting", level: 1, test: "Data centers must report electricity or water consumption to the state or a utility." },
      { id: "disclosure", label: "Public disclosure of large-load contracts or inventory", level: 1, test: "Utilities or the state must publish large-load agreements or an inventory of data centers." },
      { id: "grid-study", label: "Grid-impact study or interconnection review", level: 2, test: "Large loads must complete a study or regulator review before interconnecting." },
      { id: "siting", label: "Data-center-specific siting or environmental review", level: 2, test: "Permitting requires a review of water, noise, land, or emissions specific to data centers." },
      { id: "tariff", label: "Large-load tariff or cost allocation to operators", level: 3, test: "Regulators must set a tariff class or cost-allocation rule so operators, not other ratepayers, cover grid upgrades." },
      { id: "conditioned-incentives", label: "Incentives conditioned on efficiency or reporting", level: 3, test: "Tax incentives for data centers depend on efficiency, water, clean-energy, or reporting conditions." },
      { id: "standards", label: "Enforceable efficiency, water, or backup-power standards", level: 4, test: "Binding standards for power efficiency, water use, or on-site generation, with penalties." },
      { id: "curtailment", label: "Curtailment or demand-response obligations", level: 4, test: "Large loads must curtail or shed load on utility request during grid emergencies, with penalties." },
    ],
  },
  discrimination: {
    key: "discrimination",
    rubric: [
      "No AI-specific anti-discrimination rules.",
      "Existing civil-rights law clarified to cover algorithms.",
      "Bias audits or adverse-decision notice in one domain, such as housing or lending.",
      "Cross-sector high-risk duties: risk management, impact assessments, developer duty of care.",
      "Full high-risk regime with consumer rights and attorney general enforcement.",
    ],
    elements: [
      { id: "clarified", label: "Civil-rights law clarified to cover algorithms", level: 1, test: "A statute states that existing anti-discrimination law applies to decisions made with algorithms or AI." },
      { id: "domain-audit", label: "Bias audit or testing in one domain", level: 2, test: "Insurers, lenders, landlords, or one other sector must test AI for disparate outcomes." },
      { id: "domain-notice", label: "Adverse-decision notice in one domain", level: 2, test: "People must be told when an adverse decision in one sector used AI, with a reason." },
      { id: "high-risk", label: "Cross-sector high-risk regime with risk management", level: 3, test: "A statute defines high-risk AI across sectors and requires deployers to run a risk management program." },
      { id: "assessments", label: "Impact assessments for high-risk systems", level: 3, test: "Deployers must complete and keep impact assessments before and during use." },
      { id: "duty-of-care", label: "Developer duty of care", level: 3, test: "Developers must use reasonable care to protect people from algorithmic discrimination." },
      { id: "rights", label: "Consumer rights: correction, appeal, opt-out", level: 4, test: "People can correct data, appeal a decision, or opt out of profiling." },
      { id: "ag", label: "Attorney general enforcement with penalties", level: 4, test: "The attorney general can enforce the regime with civil penalties." },
    ],
  },
  deepfakes: {
    key: "deepfakes",
    rubric: [
      "No synthetic-media rules.",
      "Disclosure on AI-generated political ads.",
      "Bans on deceptive election deepfakes or criminal penalties for intimate deepfakes.",
      "Civil remedies for intimate imagery and digital replicas, with platform duties.",
      "Provenance requirements and likeness protections with damages.",
    ],
    elements: [
      { id: "ad-disclosure", label: "Disclosure on AI-generated political ads", level: 1, test: "Political ads containing synthetic media must carry a disclaimer." },
      { id: "election-ban", label: "Ban on deceptive election deepfakes", level: 2, test: "Deceptive synthetic media about candidates is prohibited in a window before an election, with remedies." },
      { id: "ncii-criminal", label: "Criminal penalty for non-consensual intimate deepfakes", level: 2, test: "Creating or sharing intimate synthetic images without consent is a crime." },
      { id: "csam", label: "AI-generated child sexual abuse material covered", level: 2, test: "Criminal law on child sexual abuse material expressly covers AI-generated images." },
      { id: "ncii-civil", label: "Civil remedy for intimate imagery or digital replicas", level: 3, test: "Victims can sue for damages over synthetic intimate imagery or unauthorised replicas." },
      { id: "platform", label: "Platform takedown or labeling duties", level: 3, test: "Platforms must remove reported deepfakes within a set time or label synthetic media." },
      { id: "provenance", label: "Provenance requirements for generated media", level: 4, test: "Generative tools must embed provenance data or offer detection, or distributors must preserve it." },
      { id: "likeness", label: "Voice and likeness protection with damages", level: 4, test: "Unauthorised digital replicas of a person's voice or likeness are actionable, including after death." },
    ],
  },
  employment: {
    key: "employment",
    rubric: [
      "No rules for AI in hiring or the workplace.",
      "Notice to candidates that AI screening is used.",
      "Notice plus consent or opt-out for automated decisions, and monitoring notice.",
      "Bias audits of screening tools and limits on proxy data.",
      "Audits, surveillance limits, and a private right of action.",
    ],
    elements: [
      { id: "notice", label: "Notice to candidates of AI screening", level: 1, test: "Employers must tell applicants when AI evaluates interviews, resumes, or assessments." },
      { id: "consent", label: "Consent or opt-out for automated hiring decisions", level: 2, test: "Applicants must consent to AI evaluation or can request an alternative process." },
      { id: "monitoring-notice", label: "Notice of electronic monitoring or algorithmic management", level: 2, test: "Employers must tell workers about electronic monitoring or algorithms that set pay, schedules, or discipline." },
      { id: "audits", label: "Bias audits of screening tools", level: 3, test: "Automated hiring tools must be audited for disparate impact, with results published or kept." },
      { id: "proxies", label: "Limits on proxy data for protected traits", level: 3, test: "Employers or vendors may not use data that stands in for race, sex, disability, or other protected traits." },
      { id: "surveillance", label: "Limits on workplace surveillance or algorithmic discipline", level: 4, test: "Restrictions on off-duty monitoring, biometric tracking, or discipline based solely on an algorithm." },
      { id: "pra", label: "Private right of action or agency penalties", level: 4, test: "Workers can sue, or an agency can fine, over violations of AI-in-employment rules." },
    ],
  },
  health: {
    key: "health",
    rubric: [
      "No AI-specific rules in health or insurance.",
      "Disclosure when providers or insurers use generative AI in communications.",
      "Human review of coverage denials, or insurer AI governance duties.",
      "AI may not be the sole basis for clinical or claims decisions; clinician oversight.",
      "Audit, registration, or liability regime for clinical AI.",
    ],
    elements: [
      { id: "provider-disclosure", label: "Disclosure of generative AI in patient communications", level: 1, test: "Providers must tell patients when a clinical communication was generated by AI." },
      { id: "insurer-disclosure", label: "Disclosure of AI use by insurers", level: 1, test: "Insurers must disclose when AI is used in claims or coverage communications." },
      { id: "human-review", label: "Human review of AI coverage denials", level: 2, test: "A qualified person must review utilization review or claims denials that used AI." },
      { id: "governance", label: "Insurer AI governance or regulator reporting", level: 2, test: "Insurers must maintain an AI governance program or report AI use to the insurance regulator." },
      { id: "not-sole-basis", label: "AI cannot be the sole basis for medical or claims decisions", level: 3, test: "Medical necessity, coverage, or treatment decisions cannot rest on AI alone." },
      { id: "clinician", label: "Licensed clinician oversight of AI in treatment", level: 3, test: "AI that diagnoses, prescribes, or provides therapy must operate under a licensed professional." },
      { id: "registration", label: "Audit, licensing, or registration of clinical AI", level: 4, test: "Clinical AI tools must be registered, audited, or approved by a state body." },
      { id: "liability", label: "Liability or penalties for clinical AI harm", level: 4, test: "A statute assigns liability or penalties for harm caused by clinical AI." },
    ],
  },
};

export const AREA_KEYS = Object.keys(CHECKLISTS);

export function checklistFor(area: string): AreaChecklist | undefined {
  return CHECKLISTS[area];
}
